import pytest
from ds.ds.bar_chart import create_chart


def test_check_PY_BOOK(capsys):
    create_chart()
    out, err = capsys.readouterr()
    assert '02-19 🐍.......🐍' in out
    assert '''02-13 ...........
02-14 ..............
02-15 .................
02-16 ............
02-19 🐍.......🐍
02-20 ...
02-21 ..............🐍
02-22 🐍...................
''' in out
